In [1]:
import numpy as np
import pandas as pd
import pickle
from sklearn.feature_extraction.text import TfidfTransformer
import sys
sys.path.append("../WSM2020_final_dmmig/utils/")
from recsys_metric import mrr
# print(sys.path, sys.modules)

time: 327 ms (started: 2022-06-01 15:45:43 +00:00)


# Load data

## test data

In [4]:
test_data = "leaderboard"

if test_data == "leaderboard":
    test_session = "test_leader_session.pkl"
elif test_data == "final":
    test_session = "test_session.pkl"


with open(f"./datasets/{test_session}" , "rb") as f:
    test_dic = pickle.load(f)
    
test_df = pd.DataFrame.from_dict(test_dic, orient='index')

del test_dic

time: 6.56 s (started: 2022-06-01 15:45:58 +00:00)


In [5]:
display(f"test_df: {test_df.shape}", test_df.head())
display(test_df.iloc[1,(test_df.iloc[1,:]>0).tolist()], "-"*100)

'test_df: (50000, 904)'

0    1    2    3    4    5    6    7    8    9    ...  894  895  896  \
26   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
200  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
205  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
495  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
521  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     897  898  899  900  901  902  903  
26   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
200  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
205  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
495  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
521  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 904 columns]

146    4.0
176    1.0
178    3.0
183    4.0
219    2.0
242    2.0
271    1.0
290    4.0
401    4.0
440    4.0
449    1.0
452    2.0
470    1.0
489    1.0
490    3.0
507    4.0
571    4.0
663    4.0
669    4.0
692    4.0
733    1.0
743    3.0
807    4.0
855    4.0
859    4.0
873    4.0
Name: 200, dtype: float64

'----------------------------------------------------------------------------------------------------'

time: 20.1 ms (started: 2022-06-01 15:46:05 +00:00)


## train data & candidate data

In [32]:
data_period = "1-month"

if data_period == "1-month":
    train_session = "train_session_last_1m.pkl"
    purchases_session = "purchases_session_last_1m.pkl"
    train_purchases_session = "train_purchases_session_last_1m.pkl"
    candidate_vector = "candidate_last_1m_vector"
    train_Y_date = "2021-5-1"
elif data_period == "3-month":
    train_session = "train_session_last_3m.pkl"
    purchases_session = "purchases_session_last_3m.pkl"
    train_purchases_session = "train_purchases_session_last_3m.pkl"
    candidate_vector = "candidate_last_3m_vector"
    train_Y_date = "2021-3-1"
elif data_period == "all-time":
    train_session = "train_session.pkl"
    purchases_session = "purchases_session.pkl"
    train_purchases_session = "train_purchases_session.pkl"
    candidate_vector = "candidate_vector"
    train_Y_date = "2020-1-1"
    
with open(f"./datasets/{train_session}" , "rb") as f:
    train_dic = pickle.load(f)
    
with open(f"./datasets/{purchases_session}" , "rb") as f:
    purchases_dic = pickle.load(f)
    
with open(f"./datasets/{train_purchases_session}" , "rb") as f:
    train_purchases_dic = pickle.load(f)
    

train_df= pd.DataFrame.from_dict(train_dic, orient='index')
purchases_df= pd.DataFrame.from_dict(purchases_dic, orient='index')
train_purchases_df= pd.DataFrame.from_dict(train_purchases_dic, orient='index')
del train_dic, purchases_dic, train_purchases_dic


train_Y_raw = pd.read_csv("../recsys2022/train_purchases.csv")
train_Y_raw['date'] = pd.to_datetime(train_Y_raw['date'])
train_Y = train_Y_raw.iloc[(train_Y_raw['date'] >= f'{train_Y_date}').tolist(), :]


candidate_df = pd.read_csv(f"./datasets/{candidate_vector}.csv").set_index("item_id")
candidate_ri_df = candidate_df.reset_index()

time: 35.5 s (started: 2022-06-01 16:19:05 +00:00)


In [33]:
display(f"train_df: {train_df.shape}", train_df.head(), "-"*100)
display(f"purchases_df: {purchases_df.shape}", purchases_df.head(), "-"*100)
display(f"train_purchases_df: {train_purchases_df.shape}", train_purchases_df.head(), "-"*100)
display(f"train_Y: {train_Y.shape}", train_Y, "-"*100)
display(f"candidate: {candidate_df.shape}", candidate_df.head(), "-"*100)
display(f"candidate reset index: {candidate_ri_df.shape}", candidate_ri_df.head(), "-"*100)

'train_df: (81618, 904)'

0    1    2    3    4    5    6    7    8    9    ...  894  895  896  \
113  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
115  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
261  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0  0.0   
325  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
332  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     897  898  899  900  901  902  903  
113  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
115  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
261  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
325  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
332  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 904 columns]

'----------------------------------------------------------------------------------------------------'

'purchases_df: (81618, 904)'

0    1    2    3    4    5    6    7    8    9    ...  894  895  896  \
113  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
115  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
261  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
325  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
332  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     897  898  899  900  901  902  903  
113  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
115  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
261  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
325  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
332  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 904 columns]

'----------------------------------------------------------------------------------------------------'

'train_purchases_df: (81618, 904)'

0    1    2    3    4    5    6    7    8    9    ...  894  895  896  \
113  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
115  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
261  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  2.0  0.0  0.0   
325  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
332  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     897  898  899  900  901  902  903  
113  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
115  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
261  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
325  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
332  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 904 columns]

'----------------------------------------------------------------------------------------------------'

'train_Y: (81618, 3)'

session_id  item_id                    date
17             113    21107 2021-05-05 14:15:07.278
18             115    25976 2021-05-27 10:24:05.043
44             261     8840 2021-05-31 13:44:52.368
52             325     4309 2021-05-05 10:11:06.926
53             332    25415 2021-05-25 16:24:30.224
...            ...      ...                     ...
999916     4439680    21107 2021-05-21 16:22:54.437
999957     4439823     3567 2021-05-29 16:42:31.491
999972     4439898    23993 2021-05-25 23:07:08.889
999986     4439949    16439 2021-05-12 05:49:24.294
999995     4439986     2915 2021-05-13 11:56:37.464

[81618 rows x 3 columns]

'----------------------------------------------------------------------------------------------------'

'candidate: (4223, 904)'

10_147  10_159  10_184  10_217  10_22  10_287  10_361  10_407  \
item_id                                                                  
4           0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
8           0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
9           0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
19          0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
20          0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   

         10_464  10_561  ...  7_837  7_838  8_157  8_323  8_420  8_636  9_175  \
item_id                  ...                                                    
4           0.0     0.0  ...    1.0    0.0    0.0    0.0    0.0    0.0    0.0   
8           0.0     0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9           0.0     0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
19          0.0     0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
20          0.0     0.0  ...    1.0    0.0    0.0    0.0    0.0    0.0    0.0   

         9_178  9_190  9_369  
item_id                       
4          0.0    0.0    0.0  
8          0.0    0.0    0.0  
9          0.0    0.0    0.0  
19         0.0    0.0    0.0  
20         0.0    0.0    0.0  

[5 rows x 904 columns]

'----------------------------------------------------------------------------------------------------'

'candidate reset index: (4223, 905)'

item_id  10_147  10_159  10_184  10_217  10_22  10_287  10_361  10_407  \
0        4     0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
1        8     0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
2        9     0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
3       19     0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
4       20     0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   

   10_464  ...  7_837  7_838  8_157  8_323  8_420  8_636  9_175  9_178  9_190  \
0     0.0  ...    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1     0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2     0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3     0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4     0.0  ...    1.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

   9_369  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0  

[5 rows x 905 columns]

'----------------------------------------------------------------------------------------------------'

time: 70 ms (started: 2022-06-01 16:19:41 +00:00)


## Concat raw data 

In [37]:
train_con_purchasees_df = pd.concat([train_df, purchases_df])
train_con_test_df = pd.concat([train_df, test_df])
purchases_con_test_df = pd.concat([purchases_df, test_df])
train_purchases_con_test_df = pd.concat([train_purchases_df, test_df])

time: 462 ms (started: 2022-06-01 16:19:54 +00:00)


# Build tfidf vector

- fit tfidf model
- turn `candidte_df` to tfidf vector

In [38]:
# tfidf_train_data = train_purchases_con_leader_df
# tfidf_train_data = train_con_leader_df
tfidf_train_data = train_purchases_df
# tfidf_train_data = train_df
# tfidf_train_data = purchases_df
# tfidf_train_data = train_con_purchasees_df

tfidf_model = TfidfTransformer()
tfidf_model.fit(tfidf_train_data)
candidate_tfidf_sparse_mat = tfidf_model.transform(candidate_df)
candidate_tfidf_arr = candidate_tfidf_sparse_mat.toarray()
del candidate_tfidf_sparse_mat

time: 576 ms (started: 2022-06-01 16:19:56 +00:00)


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:438: UserWarning: X has feature names, but TfidfTransformer was fitted without feature names
  warnings.warn(


In [29]:
print(f"candidate_tfidf_arr shape:{candidate_tfidf_arr.shape}")
display(candidate_tfidf_arr[0])

candidate_tfidf_arr shape:(4731, 904)


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

time: 6.16 ms (started: 2022-06-01 16:16:14 +00:00)


# Compute similarity 
- similarity bewteen session_tfidf and candidate_tfidf
- rank by similarity

In [39]:
def rank_tfidf_sim(target_df, model, overview=True):
    session_tfidf_sparse_mat = model.transform(target_df)
    session_tfidf_arr = session_tfidf_sparse_mat.toarray()
    del session_tfidf_sparse_mat
    sim_arr = np.dot(session_tfidf_arr,candidate_tfidf_arr.T) # similarity bewteen session_tfidf and candidate_tfidf
    argsort_sim_arr = np.argsort(sim_arr)[::,::-1] # rank by similarity
    item_id_rank_arr = np.apply_along_axis(lambda x:candidate_ri_df.loc[x[:100],"item_id"], 1, argsort_sim_arr).reshape(-1)
    res_df = pd.DataFrame(np.repeat(target_df.index, 100), columns=["session_id"])
    res_df["item_id"] = item_id_rank_arr
    res_df["rank"] = (list(range(1,101))*len(target_df))
    
    if (overview):
        display(f"session_tfidf_arr shape:{session_tfidf_arr.shape}",session_tfidf_arr[0], "-"*100)
        display(f"rank by similarity:", sim_arr[0][argsort_sim_arr[0]], "-"*100)
        display(f"argsort of sim_arr:", argsort_sim_arr, "-"*100)
        display(f"item_id_rank_arr[:10]:", item_id_rank_arr[:10], "-"*100)
        observe_ind = np.array([[i*100+j for j in range(10)] for i in range(len(target_df))]).reshape(-1)
        display(f"overview rank df:", res_df.iloc[observe_ind,:][:50], "-"*100)
        
    return res_df

time: 875 µs (started: 2022-06-01 16:19:58 +00:00)


# evaluation

In [40]:
eva_data = train_df
eva_label = train_Y

eva_res = rank_tfidf_sim(eva_data, tfidf_model, overview=False)
mrr_score = mrr(eva_res, eva_label, overview=False)

print(mrr_score)
display(f"eva_res shape:{eva_res.shape}", eva_res.iloc[95:105,:])

0.05128028752299939


'eva_res shape:(8161800, 3)'

session_id  item_id  rank
95          113     6319    96
96          113     8811    97
97          113    25470    98
98          113    16536    99
99          113    16947   100
100         115    19705     1
101         115    19707     2
102         115      330     3
103         115     9015     4
104         115    21735     5

time: 35 s (started: 2022-06-01 16:20:00 +00:00)


# Output results

In [42]:
res = rank_tfidf_sim(test_df, tfidf_model)
res.to_csv("./datasets/results/leader_tfidf_train_purchases_last_1_0601.csv", index=False)
del res

'session_tfidf_arr shape:(50000, 904)'

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.31890576, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

'----------------------------------------------------------------------------------------------------'

'rank by similarity:'

array([1.        , 0.95480485, 0.95259212, ..., 0.00764998, 0.00764151,
       0.00745163])

'----------------------------------------------------------------------------------------------------'

'argsort of sim_arr:'

array([[2888,  492, 2452, ..., 3347, 2232, 2566],
       [2562, 2595,  222, ..., 2058, 1344,  233],
       [1231,  975, 2630, ..., 3347, 2232, 2566],
       ...,
       [2871, 2111, 1587, ..., 1221, 3347, 1680],
       [  37, 3872, 2549, ..., 2661, 2058, 2232],
       [ 333, 1288,  315, ..., 3347, 2232, 2566]])

'----------------------------------------------------------------------------------------------------'

'item_id_rank_arr[:10]:'

array([19185,  3260, 16411, 17740, 22166, 18418, 22736,  7109,  5199,
       23612])

'----------------------------------------------------------------------------------------------------'

'overview rank df:'

session_id  item_id  rank
0            26    19185     1
1            26     3260     2
2            26    16411     3
3            26    17740     4
4            26    22166     5
5            26    18418     6
6            26    22736     7
7            26     7109     8
8            26     5199     9
9            26    23612    10
100         200    17089     1
101         200    17316     2
102         200     1382     3
103         200    23764     4
104         200     5880     5
105         200     2458     6
106         200    23160     7
107         200    25287     8
108         200     4276     9
109         200    23170    10
200         205     8194     1
201         205     6487     2
202         205    17554     3
203         205    20704     4
204         205    19143     5
205         205    28128     6
206         205    18870     7
207         205    10956     8
208         205     5553     9
209         205    13636    10
300         495    13385     1
301         495     3585     2
302         495    13006     3
303         495    24020     4
304         495    21557     5
305         495    27462     6
306         495    18028     7
307         495    13360     8
308         495    27729     9
309         495     5395    10
400         521    26471     1
401         521    12141     2
402         521     5375     3
403         521    16189     4
404         521    16162     5
405         521    27782     6
406         521     5798     7
407         521    13967     8
408         521      866     9
409         521     9634    10

'----------------------------------------------------------------------------------------------------'

time: 24.2 s (started: 2022-06-01 16:21:07 +00:00)
