In [1]:
import numpy as np
import pandas as pd
import pickle
from sklearn.feature_extraction.text import TfidfTransformer

time: 327 ms (started: 2022-05-23 16:16:54 +00:00)


# Load data

In [19]:
with open("./datasets/test_leader_session.pkl" , "rb") as f:
    test_leader_dic = pickle.load(f)
    

with open("./datasets/test_session.pkl" , "rb") as f:
    test_dic = pickle.load(f)
    

with open("./datasets/train_session.pkl" , "rb") as f:
    train_dic = pickle.load(f)

    
with open("./datasets/train_purchases_session.pkl" , "rb") as f:
    train_purchases_dic = pickle.load(f)
    
    
test_leader_df = pd.DataFrame.from_dict(test_leader_dic, orient='index')
test_df = pd.DataFrame.from_dict(test_dic, orient='index')
train_df = pd.DataFrame.from_dict(train_dic, orient='index')
train_purchases_df = pd.DataFrame.from_dict(train_purchases_dic, orient='index')

time: 5min 49s (started: 2022-05-24 05:50:31 +00:00)


In [20]:
display(test_leader_df.shape, test_leader_df.head())
display(test_leader_df.iloc[1,(test_leader_df.iloc[1,:]>0).tolist()])
display(test_df.shape, test_df.head())
display(train_df.shape, train_df.head())
display(train_purchases_df.shape, train_purchases_df.head())

(50000, 904)

0    1    2    3    4    5    6    7    8    9    ...  894  895  896  \
26   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
200  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
205  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
495  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
521  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     897  898  899  900  901  902  903  
26   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
200  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
205  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
495  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
521  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 904 columns]

146    4.0
176    1.0
178    3.0
183    4.0
219    2.0
242    2.0
271    1.0
290    4.0
401    4.0
440    4.0
449    1.0
452    2.0
470    1.0
489    1.0
490    3.0
507    4.0
571    4.0
663    4.0
669    4.0
692    4.0
733    1.0
743    3.0
807    4.0
855    4.0
859    4.0
873    4.0
Name: 200, dtype: float64

(50000, 904)

0    1    2    3    4    5    6    7    8    9    ...  894  895  896  \
61   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
96   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
185  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
224  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
285  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     897  898  899  900  901  902  903  
61   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
96   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
185  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
224  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
285  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 904 columns]

(1000000, 904)

0    1    2    3    4    5    6    7    8    9    ...  894  895  896  897  \
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  3.0  0.0  0.0  0.0   
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0  0.0   
24  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    898  899  900  901  902  903  
3   0.0  0.0  0.0  0.0  0.0  0.0  
13  0.0  0.0  0.0  0.0  0.0  0.0  
18  0.0  0.0  0.0  0.0  0.0  0.0  
19  0.0  0.0  0.0  0.0  0.0  0.0  
24  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 904 columns]

(1000000, 904)

0    1    2    3    4    5    6    7    8    9    ...  894  895  896  897  \
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
18  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  0.0   
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0  0.0   
24  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

    898  899  900  901  902  903  
3   0.0  0.0  0.0  0.0  0.0  0.0  
13  0.0  1.0  0.0  0.0  0.0  0.0  
18  0.0  0.0  0.0  0.0  0.0  0.0  
19  0.0  0.0  0.0  0.0  0.0  0.0  
24  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 904 columns]

time: 48.7 ms (started: 2022-05-24 05:56:21 +00:00)


In [22]:
candidate_df = pd.read_csv("./datasets/candidate_vector.csv").set_index("item_id")
tot_session_df =  pd.concat([test_leader_df, test_df, train_df, train_purchases_df])

time: 1.67 s (started: 2022-05-24 05:58:40 +00:00)


In [23]:
print(f"session_df shape:{tot_session_df.shape}")
display(tot_session_df.head())
print(f"candidate_df shape:{candidate_df.shape}")
display(candidate_df.head())

session_df shape:(2100000, 904)


0    1    2    3    4    5    6    7    8    9    ...  894  895  896  \
26   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
200  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
205  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
495  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
521  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     897  898  899  900  901  902  903  
26   0.0  0.0  0.0  0.0  0.0  0.0  0.0  
200  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
205  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
495  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
521  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 904 columns]

candidate_df shape:(4990, 904)


10_147  10_159  10_184  10_217  10_22  10_287  10_361  10_407  \
item_id                                                                  
4           0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
8           0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
9           0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
19          0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   
20          0.0     0.0     0.0     0.0    0.0     0.0     0.0     0.0   

         10_464  10_561  ...  7_837  7_838  8_157  8_323  8_420  8_636  9_175  \
item_id                  ...                                                    
4           0.0     0.0  ...    1.0    0.0    0.0    0.0    0.0    0.0    0.0   
8           0.0     0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
9           0.0     0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
19          0.0     0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
20          0.0     0.0  ...    1.0    0.0    0.0    0.0    0.0    0.0    0.0   

         9_178  9_190  9_369  
item_id                       
4          0.0    0.0    0.0  
8          0.0    0.0    0.0  
9          0.0    0.0    0.0  
19         0.0    0.0    0.0  
20         0.0    0.0    0.0  

[5 rows x 904 columns]

time: 23.2 ms (started: 2022-05-24 05:58:43 +00:00)


# Build tfidf vector
- turn `session_df` to tfidf vector
- turn `candidte_df` to tfidf vector

In [32]:
model = TfidfTransformer()
model.fit(tot_session_df)
session_tfidf_sparse_mat = model.transform(test_leader_df)
session_tfidf_arr = session_tfidf_sparse_mat.toarray()
candidate_tfidf_sparse_mat = model.transform(candidate_df)
candidate_tfidf_arr = candidate_tfidf_sparse_mat.toarray()

time: 10.8 s (started: 2022-05-24 06:39:28 +00:00)


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:438: UserWarning: X has feature names, but TfidfTransformer was fitted without feature names
  warnings.warn(


In [33]:
print(f"candidate_tfidf_arr shape:{candidate_tfidf_arr.shape}")
display(candidate_tfidf_arr[0])
print(f"session_tfidf_arr shape:{session_tfidf_arr.shape}")
display(session_tfidf_arr[0])

candidate_tfidf_arr shape:(4990, 904)


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

session_tfidf_arr shape:(50000, 904)


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.33980273, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

time: 9.38 ms (started: 2022-05-24 06:39:39 +00:00)


# Compute similarity 
- similarity bewteen session_tfidf and candidate_tfidf
- rank by similarity

In [34]:
sim_arr = np.dot(session_tfidf_arr,candidate_tfidf_arr.T)
candidate_ri_df = candidate_df.reset_index()
argsort_sim_arr = np.argsort(sim_arr)[::,::-1]
item_id_rank_arr = np.apply_along_axis(lambda x:candidate_ri_df.loc[x[:100],"item_id"], 1, argsort_sim_arr).reshape(-1)

time: 20.9 s (started: 2022-05-24 06:39:39 +00:00)


In [35]:
print(sim_arr.shape, sim_arr[0].max(), argsort_sim_arr.shape, argsort_sim_arr[0].max())
display(sim_arr[0][argsort_sim_arr])
display(argsort_sim_arr)
display(item_id_rank_arr[:10])

(50000, 4990) 0.9999999999999998 (50000, 4990) 4989


array([[1.        , 0.94873615, 0.94406765, ..., 0.00561194, 0.0054227 ,
        0.        ],
       [0.17777876, 0.17777876, 0.17777876, ..., 0.11737419, 0.13554003,
        0.23368116],
       [0.24818695, 0.27654104, 0.23568324, ..., 0.00591836, 0.00561194,
        0.0054227 ],
       ...,
       [0.16999575, 0.16924962, 0.13237379, ..., 0.00607783, 0.02559932,
        0.02332345],
       [0.1582438 , 0.1582438 , 0.2307034 , ..., 0.00561194, 0.0054227 ,
        0.00607783],
       [0.28509255, 0.26955859, 0.28422789, ..., 0.00591836, 0.00561194,
        0.0054227 ]])

array([[3403, 2904,  605, ..., 3041, 3952, 3584],
       [3075,  271, 4208, ..., 3806,  283, 1542],
       [1483, 2288, 1180, ..., 2196, 3041, 3952],
       ...,
       [3385, 1900, 2517, ..., 2654,  998,  514],
       [4572,   41, 3019, ..., 3041, 3952, 2654],
       [ 404, 1548,  382, ..., 2196, 3041, 3952]])

array([19185, 16411,  3260, 17740, 22166, 18418,  5199, 23612, 22736,
        7109])

time: 785 ms (started: 2022-05-24 06:40:00 +00:00)


# Output results

In [36]:
target_df = test_leader_df
res_df = pd.DataFrame(np.repeat(target_df.index, 100), columns=["session_id"])
res_df["item_id"] = item_id_rank_arr
res_df["rank"] = (list(range(1,101))*len(target_df))
res_df.to_csv("./datasets/results/leader_tfidf_tot_0524.csv", index=False)

observe_ind = np.array([[i*100+j for j in range(10)] for i in range(len(target_df))]).reshape(-1)
res_df.iloc[observe_ind,:][:50]

session_id  item_id  rank
0            26    19185     1
1            26    16411     2
2            26     3260     3
3            26    17740     4
4            26    22166     5
5            26    18418     6
6            26     5199     7
7            26    23612     8
8            26    22736     9
9            26     7109    10
100         200    17316     1
101         200     1382     2
102         200    23764     3
103         200    17089     4
104         200     5880     5
105         200     4276     6
106         200    19803     7
107         200    16660     8
108         200    23170     9
109         200     7328    10
200         205     8194     1
201         205    12879     2
202         205     6487     3
203         205    17554     4
204         205    19143     5
205         205    20704     6
206         205    28128     7
207         205     5553     8
208         205    18870     9
209         205    10956    10
300         495     6853     1
301         495    13385     2
302         495     3585     3
303         495    24020     4
304         495    13006     5
305         495    21557     6
306         495    18028     7
307         495    27462     8
308         495     5395     9
309         495    23440    10
400         521    26471     1
401         521    12141     2
402         521    14717     3
403         521    16189     4
404         521     5375     5
405         521    16162     6
406         521    27782     7
407         521      866     8
408         521     9634     9
409         521      835    10

time: 4.23 s (started: 2022-05-24 06:40:01 +00:00)
